### ISSUE TITLE
Like Not Activity Count

### ISSUE THREAD

**Issue by dpdtydz** [0sunzero0/TDP-Spring#38]
Like count가 잘 안됨

**Comment by imdduoming** [comment]
호상님 혹시 어떤 상황에서 안되는지 알 수 있을까요 ?

**Comment by dpdtydz** [comment]
로그인하고 글쓰고 로그아웃하고 다른아이디만들어서 로그인하고 글 안쓰고 바로 하트눌렀는데 작동안됫어요! 지금은 잘 고쳐졌네요
