### ISSUE TITLE
💡 idea [ View My Til]

### ISSUE THREAD

**Issue by dpdtydz** [0sunzero0/TDP-Spring#40]
공개/ 비공개 ->Til board hide

만약 Followers 라면  ? 
Following 라면 Til_user 받아와서 my til peed 노출

1. 비공개시 til following에게 보여줄지
2. 공개시 til following에게 보여줄지
3. 상관없이 무조건 folowing에게보여줄지

**Comment by imdduoming** [comment]
블로그처럼 이웃공개 / 비공개 / 모두공개 이렇게 설정하는 것도 나쁘지 않을 것 같아요 !
