### ISSUE TITLE
Comment view ERROR

### ISSUE THREAD

**Issue by dpdtydz** [0sunzero0/TDP-Spring#64]
두개의 글이 있고 두개의 계정이 있습니다.
이호상 -> sdf
이호상1 -> fdsadsdf
![image](https://user-images.githubusercontent.com/38107948/144187828-b9fcaa8f-1a91-49da-ae67-0c854b0d1079.png)

이호상의 글에 이호상1 아이디로 댓글을 달아보도록 하겠습니다.
![image](https://user-images.githubusercontent.com/38107948/144188006-eda0723e-6b8f-4182-b5b4-76313899139d.png)
작성자가 이호상1이 되는 마법입니다.

댓글을 달아보도록 하죠
![image](https://user-images.githubusercontent.com/38107948/144188083-91e7bc8c-e198-4cf7-a6e6-eea1c950d6a4.png)

But 설계 당시 왼쪽에 나오는 user 정보가 지금 로그인한 유저의 정보를 띄어주나? 라는 생각도 했지만 버그같고.

코멘트를 달고 다른 글에 접속했는데? 
아닜
![image](https://user-images.githubusercontent.com/38107948/144188188-cb58c49f-ea33-4b84-9db4-451bf344048f.png)
이호상1의 글에 이호상의 아이디로 접속 했는데? 코멘트가 그대로 있는 기적.

픽스 부탁드려요(최대한 상황설명을 자세하게 하기 위해 썻습니다ㅠㅠ)

**Comment by 0sunzero0** [comment]
호상님 알려주셔서 감사해요!
지금 detail 페이지가 해당 글의 작성자가 띄어져야 하는데, 제가 로그인한 유저 정보를 뿌려줬네요 ㅠㅠ 
내일 detail 페이지의 왼쪽 부분을 수정하겠습니다 ㅠㅠ

**Comment by 0sunzero0** [comment]
detail 페이지 user 정보 → writer 정보 뿌려주기로 변경했습니다.
KHY 브랜치에 push 했어요!
